#define nightwalk_man_balloon	0
#define nightwalk_man_walk	1
#define nightwalk_man_stepL	2
#define nightwalk_man_stepR	3
#define nightwalk_man_roll	4
#define nightwalk_man_jump	5
#define nightwalk_man_fall	6
#define nightwalk_man_balloon_l	7
#define nightwalk_man_balloon_l_swing	8
#define nightwalk_floor_00	9
#define nightwalk_floor_01	10
#define nightwalk_floor_02	11
#define nightwalk_pole_wait	12
#define nightwalk_pole_just	13
#define nightwalk_pole_miss	14
#define nightwalk_pole_through	15
#define nightwalk_pole_vanish	16
#define nightwalk_flash_00	17
#define nightwalk_flash_01	18
#define nightwalk_star_base	19
#define nightwalk_text_ab	20
#define nightwalk_effect_heart	21
#define nightwalk_effect_dot	22
#define nightwalk_firework	23
#define nightwalk_dog	24
#define nightwalk_dog_beat	25
#define nightwalk_com_walk_00	26
#define nightwalk_com_stepL_00	27
#define nightwalk_com_stepR_00	28
#define nightwalk_com_walk_01	29
#define nightwalk_com_step_01	30
#define nightwalk_cafe_00	31
#define nightwalk_cafe_01	32
#define nightwalk_com_wait_00	33
#define nightwalk_com_wait_01	34
