#define sword_bg	0
#define sword_face	1
#define sword_face_talk	2
#define sword_face_just	3
#define sword_face_breath_00	4
#define sword_face_breath_01	5
#define sword_meatball	6
#define sword_hand_l_block	7
#define sword_hand_r_block	8
#define sword_hand_l_block_just	9
#define sword_hand_r_block_just	10
#define sword_hand_l_break	11
#define sword_hand_r_break	12
#define sword_clap_effect	13
#define sword_msg_success	14
#define sword_msg_my_best	15
#define sword_body_just	16
#define sword_body_miss	17
