#define rap_body_D_B	0
#define rap_body_D	1
#define rap_body_MD_B	2
#define rap_body_MD	3
#define rap_body_H_B	4
#define rap_body_H	5
#define rap_body_S_B	6
#define rap_body_S	7
#define rap_foot_D_B	8
#define rap_foot_D	9
#define rap_foot_MD_B	10
#define rap_foot_MD	11
#define rap_foot_H_B	12
#define rap_foot_H	13
#define rap_foot_S_B	14
#define rap_foot_S	15
#define rap_foot_beat	16
#define rap_P_head	17
#define rap_P_cough	18
#define rap_C_head	19
#define rap_C_head_through_D	20
#define rap_C_head_through_MD	21
#define rap_C_head_through_H	22
#define rap_C_head_through_S	23
#define rap_eye_D_B	24
#define rap_eye_D	25
#define rap_eye_D_arrange	26
#define rap_eye_MD_B	27
#define rap_eye_MD	28
#define rap_eye_H_B	29
#define rap_eye_H	30
#define rap_eye_S_B	31
#define rap_eye_S	32
#define rap_mouth_D_B	33
#define rap_mouth_D	34
#define rap_mouth_MD_B	35
#define rap_mouth_MD	36
#define rap_mouth_MD_ura	37
#define rap_mouth_H_B	38
#define rap_mouth_H	39
#define rap_mouth_H_ura	40
#define rap_mouth_S_B	41
#define rap_mouth_S	42
#define rap_girl_body_blow_loop	43
#define rap_girl_body_blow_end	44
#define rap_girl_body_D_B	45
#define rap_girl_body_D	46
#define rap_girl_body_MD_B	47
#define rap_girl_body_MD	48
#define rap_girl_body_H_B	49
#define rap_girl_body_H	50
#define rap_girl_body_S_B	51
#define rap_girl_body_S	52
#define rap_girl_foot_D_B	53
#define rap_girl_foot_D	54
#define rap_girl_foot_MD_B	55
#define rap_girl_foot_MD	56
#define rap_girl_foot_H_B	57
#define rap_girl_foot_H	58
#define rap_girl_foot_S_B	59
#define rap_girl_foot_S	60
#define rap_girl_foot_beat	61
#define rap_girl_eye_D_B	62
#define rap_girl_eye_D	63
#define rap_girl_eye_MD_B	64
#define rap_girl_eye_MD	65
#define rap_girl_eye_H_B	66
#define rap_girl_eye_H	67
#define rap_girl_eye_S_B	68
#define rap_girl_eye_S	69
#define rap_girl_mouth_D_B	70
#define rap_girl_mouth_D	71
#define rap_girl_mouth_MD_B	72
#define rap_girl_mouth_MD	73
#define rap_girl_mouth_MD_ura	74
#define rap_girl_mouth_H_B	75
#define rap_girl_mouth_H	76
#define rap_girl_mouth_H_ura	77
#define rap_girl_mouth_S_B	78
#define rap_girl_mouth_S	79
#define rap_car_beat	80
#define rap_car_shadow	81
#define rap_car_light	82
