#define samurai_samurai_beat	0
#define samurai_samurai_ready	1
#define samurai_samurai_slash	2
#define samurai_samurai_slash2	3
#define samurai_samurai_slash_out	4
#define samurai_samurai_slash2_out	5
#define samurai_samurai_roll_start	6
#define samurai_samurai_roll_loop	7
#define samurai_samurai_roll_pose	8
#define samurai_samurai_roll_end	9
#define samurai_samurai_tumble	10
#define samurai_samurai_tumble2	11
#define samurai_samurai_damage	12
#define samurai_samurai_damage2	13
#define samurai_samurai_go	14
#define samurai_samurai_come	15
#define samurai__samurai_slash3	16
#define samurai__test_samurai	17
#define samurai__samurai_tumble_old	18
#define samurai__samurai_slash2_old	19
