#define birds_i_R_beat	0
#define birds_i_R_walk_00	1
#define birds_i_R_walk_01	2
#define birds_i_R_squat	3
#define birds_i_R_jump	4
#define birds_i_R_jump_miss	5
#define birds_i_L_beat	6
#define birds_i_L_walk_00	7
#define birds_i_L_walk_01	8
#define birds_i_L_squat	9
#define birds_i_L_jump	10
#define birds_i_L_jump_miss	11
#define birds_i_miss_back	12
#define birds_i_miss_front	13
#define birds_i_muka	14
#define birds_i_miss_squat	15
#define birds_i_fly	16
#define birds_i_fly_loop	17
#define birds_i_land	18
#define birds_i__miss_back	19
#define birds_i__miss_front	20
