#ifndef GAME_AGBTAP_MYFLOWDECL_HPP
#define GAME_AGBTAP_MYFLOWDECL_HPP

#include <revolution/types.h>

#include "ExFlowDecl.hpp"

#include "AgbTap/SceneAgbTap.hpp" // EAgbTapMove

// TODO: add naming, comments & macros ..

enum {
    /*   AgbTap MyFlow opcodes (0x200)  */

    TF_AGBTAP_INPUT = 0x200,
    TF_AGBTAP_BEAT_ANIM,
    TF_AGBTAP_SET_ANIME_MONKEY,
    TF_AGBTAP_SET_ANIME_GIRL,
    TF_AGBTAP_RESET_PERFORMANCE,
    TF_AGBTAP_GIRAFFE_MOVE,
    TF_AGBTAP_GIRAFFE_ANIM,
    TF_AGBTAP_SET_BALLOON_TARGET
};

// command macros

#define TFC_AGBTAP_INPUT() TFD_CMD(TF_AGBTAP_INPUT, 0, 0),

#define TFC_AGBTAP_BEAT_ANIM() TFD_CMD(TF_AGBTAP_BEAT_ANIM, 0, 0),

// see EAgbTapMove
#define TFC_AGBTAP_SET_ANIME_MONKEY(type) TFD_CMD(TF_AGBTAP_SET_ANIME_MONKEY, 1, 0), TFD_CAST(type),
// see EAgbTapMove
#define TFC_AGBTAP_SET_ANIME_GIRL(type) TFD_CMD(TF_AGBTAP_SET_ANIME_GIRL, 1, 0), TFD_CAST(type),

#define TFC_AGBTAP_RESET_PERFORMANCE() TFD_CMD(TF_AGBTAP_RESET_PERFORMANCE, 0, 0),

#define TFC_AGBTAP_GIRAFFE_MOVE_OUT() TFD_CMD(TF_AGBTAP_GIRAFFE_MOVE, 0, 1),
#define TFC_AGBTAP_GIRAFFE_MOVE_IN() TFD_CMD(TF_AGBTAP_GIRAFFE_MOVE, 0, 0),

#define TFC_AGBTAP_GIRAFFE_ANIM_NORMAL() TFD_CMD(TF_AGBTAP_GIRAFFE_ANIM, 0, 0),
#define TFC_AGBTAP_GIRAFFE_ANIM_GOOD(maxMissTapCount) TFD_CMD(TF_AGBTAP_GIRAFFE_ANIM, 1, 1), TFD_CAST(maxMissTapCount),
#define TFC_AGBTAP_GIRAFFE_ANIM_BAD() TFD_CMD(TF_AGBTAP_GIRAFFE_ANIM, 0, 2),

#define TFC_AGBTAP_SET_BALLOON_TARGET_MONKEYS() TFD_CMD(TF_AGBTAP_SET_BALLOON_TARGET, 0, 0),
#define TFC_AGBTAP_SET_BALLOON_TARGET_GIRAFFE() TFD_CMD(TF_AGBTAP_SET_BALLOON_TARGET, 0, 1),

#endif
