#define tambourine_monkey_beat	0
#define tambourine_monkey_talk	1
#define tambourine_monkey_talk_long	2
#define tambourine_monkey_swing	3
#define tambourine_monkey_hit	4
#define tambourine_monkey_hit_long	5
#define tambourine_monkey_face_normal	6
#define tambourine_monkey_face_happy	7
#define tambourine_monkey_face_bad	8
#define tambourine_monkey_face_talk	9
#define tambourine_monkey_face_talk_long	10
#define tambourine_monkey_face_act	11
#define tambourine_monkey_face_swing_look	12
#define tambourine_monkey_face_hit_look	13
#define tambourine_you_swing	14
#define tambourine_you_hit	15
#define tambourine_you_beat	16
#define tambourine_waste_can	17
#define tambourine_flower	18
#define tambourine_bg	19
#define tambourine_test_tambourine	20
#define tambourine__monkey_swing	21
#define tambourine__monkey_swing02	22
#define tambourine__monkey_swing_look	23
#define tambourine__monkey_hit_look	24
#define tambourine_you_swing_	25
