#define eatmen_a_body	0
#define eatmen_a_face_beat	1
#define eatmen_a_face_happy	2
#define eatmen_a_face_sad	3
#define eatmen_a_face_blow	4
#define eatmen_a_face_blow_loop	5
#define eatmen_a_face_blow_loop_end	6
#define eatmen_a_hand_ready	7
#define eatmen_a_hand_blow	8
#define eatmen_b_body_beat	9
#define eatmen_b_body_happy	10
#define eatmen_b_body_sad	11
#define eatmen_b_body_talk	12
#define eatmen_b_body_catch	13
#define eatmen_b_body_eat	14
#define eatmen_b_body_miss	15
#define eatmen_b_body_out	16
#define eatmen_b_body_sad_loop	17
#define eatmen_b_body_gameover	18
#define eatmen_b_face_catch	19
#define eatmen_b_face_catch_effect	20
#define eatmen_b_hand_f_up	21
#define eatmen_b_hand_f_set	22
#define eatmen_b_hand_f_out	23
#define eatmen_b_hand_b_up	24
#define eatmen_b_hand_b_set	25
#define eatmen_b_hand_b_out	26
#define eatmen_food_L	27
#define eatmen_food_S	28
#define eatmen_life_get	29
#define eatmen_life_lost	30
#define eatmen_effect	31
#define eatmen_breath	32
