#define concons_shuttle_pole_down	0
#define concons_shuttle_just	1
#define concons_shuttle_miss	2
#define concons_pole	3
#define concons_concon_just	4
#define concons_concon_miss	5
#define concons_concon_out	6
#define concons_concon_pre_motion	7
#define concons_dummy	8
#define concons_effect_00_f	9
#define concons_effect_00_b	10
#define concons_alien_beat_inst	11
#define concons_alien_beat_real	12
#define concons_alien_hit	13
#define concons_alien_hit_after	14
#define concons_alien_wait	15
#define concons_alien_talk	16
#define concons_smog_just_L	17
#define concons_smog_just_S	18
#define concons_smog_blur	19
