#define karateman_Face	0
#define karateman_Wait	1
#define karateman_Beat	2
#define karateman_Beat2	3
#define karateman_Jab	4
#define karateman_Straight	5
#define karateman_Straight2	6
#define karateman_LowJab	7
#define karateman_LowKick	8
#define karateman_LowKickMiss	9
#define karateman_BackHand	10
#define karateman_UpperCut	11
#define karateman_ToReady	12
#define karateman_Item	13
#define karateman_ItemShadow	14
#define karateman_ItemBarrel	15
#define karateman_HitMark	16
#define karateman_HitPosition	17
#define karateman_Word	18
#define karateman_effect	19
#define karateman_TestComboFull	20
