#define agb_tap_bg	0
#define agb_tap_bg_frame	1
#define agb_tap_girl_beat	2
#define agb_tap_girl_ready_L	3
#define agb_tap_girl_ready_R	4
#define agb_tap_girl_tap_0L	5
#define agb_tap_girl_tap_0R	6
#define agb_tap_girl_charge	7
#define agb_tap_girl_tap_1L	8
#define agb_tap_girl_tap_1R	9
#define agb_tap_girl_crouch	10
#define agb_tap_girl_jump	11
#define agb_tap_girl_pause	12
#define agb_tap_girl_pause_miss	13
#define agb_tap_girl_round	14
#define agb_tap_girl_land	15
#define agb_tap_girl_land_miss	16
#define agb_tap_monkey_beat	17
#define agb_tap_monkey_ready_L	18
#define agb_tap_monkey_ready_R	19
#define agb_tap_monkey_tap_0L	20
#define agb_tap_monkey_tap_0R	21
#define agb_tap_monkey_charge	22
#define agb_tap_monkey_tap_1L	23
#define agb_tap_monkey_tap_1R	24
#define agb_tap_monkey_crouch	25
#define agb_tap_monkey_jump	26
#define agb_tap_monkey_pause	27
#define agb_tap_monkey_round	28
#define agb_tap_monkey_land	29
#define agb_tap_giraffe_nice	30
#define agb_tap_giraffe_normal	31
#define agb_tap_giraffe_bad	32
#define agb_tap_shadow	33
