#define seesaw_bg	0
#define seesaw_ground	1
#define seesaw_jump_just_out_in	2
#define seesaw_jump_just_out_in_big	3
#define seesaw_jump_just_out_out	4
#define seesaw_jump_just_out_out_big	5
#define seesaw_jump_just_in_out	6
#define seesaw_jump_just_in_in	7
#define seesaw_jump_miss_out	8
#define seesaw_jump_miss_in	9
#define seesaw_land_just_out	10
#define seesaw_land_just_out_big	11
#define seesaw_land_just_in	12
#define seesaw_land_just_in_big	13
#define seesaw_land_miss_out	14
#define seesaw_land_miss_in	15
#define seesaw_land_through_out	16
#define seesaw_land_through_in	17
#define seesaw_roll_out_in	18
#define seesaw_roll_out_in_big	19
#define seesaw_roll_in_out	20
#define seesaw_beat	21
#define seesaw_beat_guitar_stroke	22
#define seesaw_beat_guitar_choke	23
#define seesaw_beat_guitar_choke_loop	24
#define seesaw_beat2	25
#define seesaw_beat_guitar_stroke2	26
#define seesaw_beat_guitar_choke2	27
#define seesaw_beat_guitar_choke_loop2	28
#define seesaw_burst	29
#define seesaw_wait	30
#define seesaw_fraction_w	31
#define seesaw_fraction_b	32
#define seesaw_ball_w	33
#define seesaw_ball_b	34
#define seesaw_spark	35
