#define metronome_dummy	0
#define metronome_bg	1
#define metronome_monitor	2
#define metronome_plot	3
#define metronome_plot_shot	4
#define metronome_plot_aim	5
#define metronome_button	6
#define metronome_sign_note	7
#define metronome_sign_frame	8
#define metronome_sign_frame_0	9
#define metronome_sign_number	10
#define metronome_sign_measure	11
#define metronome_spot_show	12
#define metronome_spot_hide	13
#define metronome_curtain_L	14
#define metronome_curtain_R	15
#define metronome_aim_top	16
#define metronome_aim_bottom	17
#define metronome_space	18
#define metronome_test	19
