#define boat_sign_signboard_attention	0
#define boat_sign_signboard_direction	1
#define boat_sign_sign	2
#define boat_sign_sign_stop	3
#define boat_sign_pig_stand	4
#define boat_sign_pig_squat	5
#define boat_sign_pig_landing	6
#define boat_sign_pig_walk	7
#define boat_sign_sample	8
#define boat_sign_pier	9
#define boat_sign_pier_part	10
#define boat_sign_pier_part_stand	11
#define boat_sign_pier_effect	12
#define boat_sign_obj_ring	13
#define boat_sign_pig_splash	14
#define boat_sign_pig_thanks	15
#define boat_sign_pier_code_sa	16
#define boat_sign_pier_code_mu	17
#define boat_sign_pier_code_ra	18
#define boat_sign_pier_code_i	19
#define boat_sign_pier_code_go	20
#define boat_sign_pier_code_ru	21
#define boat_sign_pier_code_fu	22
#define boat_sign_obj_rock	23
#define boat_sign_obj_needle	24
#define boat_sign_obj_bom	25
