#define golf_monkey_monkey_beat	0
#define golf_monkey_monkey_wait	1
#define golf_monkey_monkey_ready_S	2
#define golf_monkey_monkey_ready_L	3
#define golf_monkey_monkey_pitch	4
#define golf_monkey_monkey_turn	5
#define golf_monkey_monkey_inst_wait	6
#define golf_monkey_monkey_inst_talk	7
#define golf_monkey_monkey_inst_blink	8
#define golf_monkey_monkey_inst_lets	9
#define golf_monkey_monkey_inst_sorry	10
#define golf_monkey_monkey_inst_osii	11
#define golf_monkey_monkey_inst_dodo	12
#define golf_monkey_monkey_inst_good	13
#define golf_monkey_monkey_inst_uhouho	14
#define golf_monkey_monkey_effect	15
#define golf_monkey_monkey_shadow	16
#define golf_monkey_monkey_face_just	17
#define golf_monkey_monkey_face_miss	18
#define golf_monkey_monkey_face_sad	19
#define golf_monkey_monkey_face_talk	20
#define golf_monkey_gorilla_beat_0	21
#define golf_monkey_gorilla_beat_1	22
#define golf_monkey_gorilla_beat_2	23
#define golf_monkey_gorilla_ready_00	24
#define golf_monkey_gorilla_ready_01	25
#define golf_monkey_gorilla_ready_02	26
#define golf_monkey_gorilla_pitch	27
#define golf_monkey_gorilla_inst_talk	28
#define golf_monkey_gorilla_inst_uhouho	29
#define golf_monkey_gorilla_inst_sorry	30
#define golf_monkey_gorilla_shadow	31
#define golf_monkey_ball_S	32
#define golf_monkey_ball_L	33
#define golf_monkey_ball_spin_S	34
#define golf_monkey_ball_spin_L	35
#define golf_monkey_ball_shadow_S	36
#define golf_monkey_ball_shadow_L	37
#define golf_monkey__monkey_face_happy_00	38
#define golf_monkey__monkey_face_happy_01	39
#define golf_monkey__monkey_inst_good	40
