#define golf_bg_bg_sky	0
#define golf_bg_bg_cloud	1
#define golf_bg_bg_airplane	2
#define golf_bg_bg_bird	3
#define golf_bg_bg_sea_gull	4
#define golf_bg_bg_sea	5
#define golf_bg_bg_island	6
#define golf_bg_bg_ground	7
#define golf_bg_ball	8
#define golf_bg_leaf_00	9
#define golf_bg_leaf_01	10
#define golf_bg_leaf_02	11
#define golf_bg_ball_S_OK	12
#define golf_bg_ball_L_OK	13
#define golf_bg_ball_S_through	14
#define golf_bg_ball_L_through	15
#define golf_bg_zoom_00	16
#define golf_bg_zoom_01	17
#define golf_bg_zoom_02	18
#define golf_bg_zoom_03	19
#define golf_bg_zoom_04	20
#define golf_bg_whale_wait	21
#define golf_bg_whale_OK	22
#define golf_bg_whale_hide	23
#define golf_bg_splash_00	24
#define golf_bg_splash_01	25
#define golf_bg_splash_02	26
#define golf_bg_test_00	27
