#define samurai_enemy_enemy_00	0
#define samurai_enemy_enemy_00_eye	1
#define samurai_enemy_enemy_00_shake	2
#define samurai_enemy_enemy_00_just_l	3
#define samurai_enemy_enemy_00_just_r	4
#define samurai_enemy_enemy_00_miss	5
#define samurai_enemy_enemy_00_through	6
#define samurai_enemy_enemy_01	7
#define samurai_enemy_enemy_01_eye	8
#define samurai_enemy_enemy_01_shake	9
#define samurai_enemy_enemy_01_just_l	10
#define samurai_enemy_enemy_01_just_r	11
#define samurai_enemy_enemy_01_miss	12
#define samurai_enemy_enemy_01_through	13
#define samurai_enemy_enemy_02	14
#define samurai_enemy_enemy_02_eye	15
#define samurai_enemy_enemy_02_shake	16
#define samurai_enemy_enemy_02_just_l	17
#define samurai_enemy_enemy_02_just_r	18
#define samurai_enemy_enemy_02_miss	19
#define samurai_enemy_enemy_02_through	20
#define samurai_enemy_enemy_03	21
#define samurai_enemy_enemy_03_eye	22
#define samurai_enemy_enemy_03_shake	23
#define samurai_enemy_enemy_03_just_l	24
#define samurai_enemy_enemy_03_just_r	25
#define samurai_enemy_enemy_03_miss	26
#define samurai_enemy_enemy_03_through	27
#define samurai_enemy_enemy_10	28
#define samurai_enemy_enemy_10_eye	29
#define samurai_enemy_enemy_10_just_l	30
#define samurai_enemy_enemy_10_just_r	31
#define samurai_enemy_enemy_10_miss	32
#define samurai_enemy_enemy_10_through	33
#define samurai_enemy_enemy_10_trajectory	34
#define samurai_enemy_smog00	35
#define samurai_enemy_smog01	36
#define samurai_enemy_smog10	37
#define samurai_enemy_smog11	38
#define samurai_enemy_smog_base	39
#define samurai_enemy_windmill	40
#define samurai_enemy_enemy_inst_demo	41
