#define tap_spot	0
#define tap_foot_offset	1
#define tap_Default	2
#define tap_Beat	3
#define tap_L_Up	4
#define tap_L_UpWithHitR	5
#define tap_L_UpWithHitL	6
#define tap_L_UpWithHitL2	7
#define tap_L_BackWithHitL	8
#define tap_L_BackWithHitR	9
#define tap_L_BackToeKick	10
#define tap_L_PullStartWithHitR	11
#define tap_L_PullWithHitR	12
#define tap_L_Down	13
#define tap_R_Up	14
#define tap_R_UpWithHitL	15
#define tap_R_UpWithHitR	16
#define tap_R_UpWithHitR2	17
#define tap_R_BackWithHitR	18
#define tap_R_BackWithHitL	19
#define tap_R_BackToeKick	20
#define tap_R_PullStartWithHitL	21
#define tap_R_PullWithHitL	22
#define tap_R_Down	23
#define tap_frame_top	24
#define tap_frame_bottom	25
#define tap_Body	26
#define tap_Body_Far	27
#define tap_TestBeat	28
#define tap_TestStepM	29
#define tap_TestScoreM	30
#define tap_TestStepS	31
#define tap_TestStepS2	32
#define tap_TestScoreS	33
#define tap_TestStepL	34
#define tap_TestScoreL	35
