#include "Script/Grading.hpp"

#include <revolution/WPAD.h>

#include "Grading/MyFlowDecl.hpp"

#include "ExFlow.hpp"

#include "SceneManager.hpp"

#include "CheckPointManager.hpp"

#include "rev_tengoku.rsid"

TFD_BEGIN(lbl_801F97A0)
    TFC_CATEGORY(0)
    TFC_SND_LOADING_BEGIN()
    TFC_REST(12)
    TFC_RESET_SND_GROUP_HEAP_0()
    TFC_RESET_SND_GROUP_HEAP_1()
    TFC_RESET_SND_GROUP_HEAP_2()
    TFC_RESET_SND_GROUP_HEAP_3()
    TFC_LOAD_SND_GROUP_1(GROUP_RESULT)
    TFC_CALL(lbl_802E4CE8)
    TFC_SND_LOADING_END()
TFD_STOP()

TFD_BEGIN(lbl_801F97E0)
    TFC_CATEGORY(0)
    TFC_TEMPO(120)
    TFC_SPEED(256)
    TFC_ASYNC_CALL(lbl_801F97A0, 0)
    TFC_SET_SCENE_VER(eScene_Grading, 0)
    TFC_SET_SCENE(eScene_Grading, NULL)
    TFC_REST(48)
    TFC_FADE_IN_FRAMES(1)
    TFC_REST(48)
    TFC_CALL(lbl_802559B0)
    TFC_LABEL(1234)
    TFC_REST(12)
    TFC_GET_SCENE_RUNNING()
    TFC_IF_EQU(FALSE)
        TFC_JUMP(1234)
    TFC_ENDIF()
    TFC_GRADING_SHOW_CAPTION()
    TFC_PLAY_SFX(SE_RESULT_MES_STEP1)
    TFC_REST(48)
    TFC_REST(48)
    TFC_REST(48)
    TFC_GRADING_SHOW_COMMENT()
    TFC_PLAY_SFX(SE_RESULT_MES_STEP2)
    TFC_REST(48)
    TFC_REST(48)
    TFC_REST(48)
    TFC_REST(48)
    TFC_REST(24)
    TFC_GRADING_SHOW_GRADE()
    TFC_CHECKPOINT_GET_GRADE()
    TFC_IF_EQU(eGrade_HI)
        TFC_PREPARE_WAVE(WSD_RESULT_HI_LEVEL)
    TFC_ENDIF()
    TFC_CHECKPOINT_GET_GRADE()
    TFC_IF_EQU(eGrade_OK)
        TFC_PREPARE_WAVE(WSD_RESULT_HEIBON)
    TFC_ENDIF()
    TFC_CHECKPOINT_GET_GRADE()
    TFC_IF_EQU(eGrade_NG)
        TFC_PREPARE_WAVE(WSD_RESULT_YARINAOSI)
    TFC_ENDIF()
    TFC_REST(48)
    TFC_REST(48)
    TFC_GRADING_CHECK_FOLLOW()
    TFC_IF_EQU(TRUE)
        TFC_GRADING_SHOW_FOLLOW()
        TFC_PLAY_SFX(SE_RESULT_MES_ADD)
        TFC_REST(48)
    TFC_ENDIF()
    TFC_REST_FRAMES(30)
    TFC_CALL(lbl_802E4CC0)
    TFC_START_PREPARED_WAVE()
    TFC_REST(48)
    TFD_CMD(0x123, 1, 0), 48,
    TFC_BUTTON_PROMPT_SETUP(WPAD_BUTTON_A, SE_SKIP_ON, SE_SKIP_OFF)
    TFC_CALL(lbl_802E4CA0)
    TFD_CMD(0x123, 0, 1),
    TFC_CALL(lbl_80255990)
    TFC_STOP_WAVE(60)
    TFC_REST(72)
TFD_RETURN()
