#define basket_bg	0
#define basket_com_dribble	1
#define basket_com_ready	2
#define basket_com_pass	3
#define basket_com_miss	4
#define basket_you_wait	5
#define basket_you_beat	6
#define basket_you_swing	7
#define basket_you_catch	8
#define basket_you_miss	9
#define basket_you_shot	10
#define basket_goal_just	11
#define basket_goal_just_front	12
#define basket_goal_miss	13
#define basket_goal_miss_front	14
#define basket_ball	15
#define basket_balls	16
#define basket_shadow	17
#define basket_sample	18
