#define karateman2_Face	0
#define karateman2_Wait	1
#define karateman2_Beat	2
#define karateman2_Beat2	3
#define karateman2_Jab	4
#define karateman2_Straight	5
#define karateman2_Straight2	6
#define karateman2_LowJab	7
#define karateman2_LowKick	8
#define karateman2_LowKickMiss	9
#define karateman2_BackHand	10
#define karateman2_UpperCut	11
#define karateman2_ToReady	12
#define karateman2_Item	13
#define karateman2_ItemShadow	14
#define karateman2_ItemBarrel	15
#define karateman2_HitMark	16
#define karateman2_HitPosition	17
#define karateman2_Word	18
#define karateman2_effect	19
#define karateman2_TestComboFull	20
