#define permanent_next	0
#define permanent_next_loop	1
#define permanent_skip	2
#define permanent_skip_practice	3
#define permanent_inst_example	4
#define permanent_inst_example_msg	5
#define permanent_skip_base	6
#define permanent_pause_in	7
#define permanent_pause_out	8
#define permanent_pause_base	9
#define permanent_exit	10
#define permanent_to_menu	11
#define permanent_remain	12
#define permanent_remain_number	13
#define permanent_you	14
#define permanent_you_1P	15
#define permanent_you_2P	16
#define permanent_number	17
#define permanent_dot	18
#define permanent_pts	19
#define permanent_inst_loop	20
#define permanent_meter	21
#define permanent_mark_L	22
#define permanent_mark_S	23
#define permanent_tutorial	24
#define permanent_mark_NG	25
#define permanent_mask	26
#define permanent_canvas	27
#define permanent_perfect_icon_hit	28
#define permanent_perfect_icon_fail	29
#define permanent_perfect_msg_loop	30
#define permanent_frame_inst	31
#define permanent_frame_video_fade_in	32
#define permanent_frame_video_fade_out	33
#define permanent_save	34
