#define panel_turn_W2B_just	0
#define panel_turn_B2W_just	1
#define panel_turn_W2W_just	2
#define panel_turn_B2B_just	3
#define panel_turn_W2B_miss	4
#define panel_turn_B2W_miss	5
#define panel_turn_W2W_miss	6
#define panel_turn_B2B_miss	7
#define panel_turn_W_through	8
#define panel_turn_B_through	9
#define panel_turn_W2B_out	10
#define panel_turn_B2W_out	11
#define panel_turn_W2W_out	12
#define panel_turn_B2B_out	13
#define panel_turning_from_W	14
#define panel_turning_from_B	15
#define panel_open	16
#define panel_open_miss	17
#define panel_yeah_W	18
#define panel_yeah_B	19
#define panel_beat_W	20
#define panel_beat_B	21
#define panel_beat_1st	22
#define panel_bg	23
#define panel_face_P	24
#define panel_face_C	25
#define panel_hair_front	26
#define panel_hair_back	27
#define panel_mouth	28
#define panel_mouth_lip_sync_ao	29
#define panel_mouth_lip_sync_ie	30
#define panel_mouth_lip_sync_u	31
#define panel_effect_W	32
#define panel_effect_B	33
