#define kungfu_dummy	0
#define kungfu_bamboo	1
#define kungfu_tsubo	2
#define kungfu_effect_hit	3
#define kungfu_ball	4
#define kungfu_beat	5
#define kungfu_jump	6
#define kungfu_jump_miss	7
#define kungfu_jump_toge	8
#define kungfu_fire_just	9
#define kungfu_fire_miss	10
#define kungfu_fire_head_just	11
#define kungfu_fire_head_miss	12
#define kungfu_back_round	13
#define kungfu_front_round	14
#define kungfu_hand_stand_beat	15
#define kungfu_hand_stand_jump	16
#define kungfu_hand_stand_jump_miss	17
#define kungfu_hand_stand_fire_just	18
#define kungfu_dragon_just	19
#define kungfu_dragon_miss	20
#define kungfu_dragon	21
#define kungfu_dragon_fire	22
#define kungfu_dragon_fire_head	23
#define kungfu_dragon_fire_miss	24
#define kungfu_koge_particle	25
#define kungfu_ball_fire	26
#define kungfu_toge	27
#define kungfu_toge_fire	28
#define kungfu_toge_koge	29
#define kungfu_fire_ready	30
#define kungfu_hand_stand_fire_ready	31
#define kungfu_dragon_fire_ready	32
#define kungfu_kick	33
#define kungfu_dragon_stand	34
#define kungfu_dragon_squat	35
#define kungfu_dragon_stretch	36
#define kungfu_dragon_attack	37
#define kungfu_volley_sky	38
#define kungfu_volley_attack	39
#define kungfu_volley_miss	40
#define kungfu_kick_through	41
#define kungfu_through	42
#define kungfu_volley_ready	43
#define kungfu_volley_charge	44
#define kungfu_volley_charge_miss	45
#define kungfu_kick_miss	46
#define kungfu_rei	47
#define kungfu_dragon_fire_ng	48
#define kungfu_kick_beat	49
#define kungfu_shock	50
#define kungfu_fall	51
#define kungfu__fire_just	52
#define kungfu__fire_miss	53
