#define kungfu_objects_ball	0
#define kungfu_objects_ball_fire_effect	1
#define kungfu_objects_smoke	2
#define kungfu_objects_dragon_effect	3
#define kungfu_objects_item_code	4
#define kungfu_objects_code_character	5
#define kungfu_objects_item_food	6
#define kungfu_objects_sennin	7
#define kungfu_objects_CellAnim0	8
#define kungfu_objects_ball_gold	9
#define kungfu_objects_ball_silver	10
#define kungfu_objects_ball_copper	11
#define kungfu_objects_rubbish_gold	12
#define kungfu_objects_rubbish_silver	13
#define kungfu_objects_rubbish_copper	14
#define kungfu_objects_ball_gold_clush	15
#define kungfu_objects_ball_gold_piece	16
#define kungfu_objects_ball_silver_piece	17
#define kungfu_objects_ball_copper_piece	18
#define kungfu_objects_CellAnim1	19
#define kungfu_objects_cucumber	20
#define kungfu_objects_blinking_ball	21
#define kungfu_objects_kappa	22
#define kungfu_objects_kappa_beat	23
#define kungfu_objects_kappa_hide	24
#define kungfu_objects_bycicle	25
#define kungfu_objects_coin	26
#define kungfu_objects_fish	27
#define kungfu_objects_line	28
#define kungfu_objects_dummy	29
#define kungfu_objects_bycicle_code	30
#define kungfu_objects_kappa_2	31
#define kungfu_objects_kappa_hide_2	32
#define kungfu_objects_bycicle_2	33
#define kungfu_objects_water_action	34
#define kungfu_objects_kappa_throw	35
#define kungfu_objects_kappa_clap	36
#define kungfu_objects_kappa_smile	37
