#define kungfu_bg_l_2_pond	0
#define kungfu_bg_l_2_crowd_stop	1
#define kungfu_bg_l_2_crowd1_shout	2
#define kungfu_bg_l_2_crowd2_shout	3
#define kungfu_bg_l_2_crowd1_shout_right	4
#define kungfu_bg_l_2_crowd1_shout_left	5
#define kungfu_bg_l_2_crowd2_shout_right	6
#define kungfu_bg_l_2_crowd2_shout_left	7
#define kungfu_bg_l_2_crowd3_center	8
#define kungfu_bg_l_2_crowd4_on_the_gate	9
#define kungfu_bg_l_2_crowd5_in_the_restaurant	10
#define kungfu_bg_l_2_crowd6_in_the_building	11
#define kungfu_bg_l_2_crowd5_1	12
#define kungfu_bg_l_2_croud5_2	13
#define kungfu_bg_l_2_crowd7	14
#define kungfu_bg_l_2_crowd8	15
#define kungfu_bg_l_2_center_a	16
#define kungfu_bg_l_2_side_a_right	17
#define kungfu_bg_l_2_side_a_left	18
#define kungfu_bg_l_2_shop	19
#define kungfu_bg_l_2_building	20
#define kungfu_bg_l_2_building_2f	21
#define kungfu_bg_l_2_side_b_right	22
#define kungfu_bg_l_2_side_b_left	23
#define kungfu_bg_l_2_center_b_right	24
#define kungfu_bg_l_2_center_b_left	25
#define kungfu_bg_l_2_gate	26
#define kungfu_bg_l_2_gate_2	27
#define kungfu_bg_l_2_gate_3	28
#define kungfu_bg_l_2_shop_pos	29
