#define robot_shadow_bg	0
#define robot_shadow_belt_loop	1
#define robot_shadow_belt_screw_loop	2
#define robot_shadow_arm_base	3
#define robot_shadow_arm_ready	4
#define robot_shadow_arm_down_just_1	5
#define robot_shadow_arm_down_just_2	6
#define robot_shadow_arm_down_miss_f_1	7
#define robot_shadow_arm_down_miss_f_2	8
#define robot_shadow_arm_down_miss_b_1	9
#define robot_shadow_arm_down_miss_b_2	10
#define robot_shadow_arm_down_out	11
#define robot_shadow_arm_down_fail_a	12
#define robot_shadow_arm_down_fail_b	13
#define robot_shadow_arm_roll_1	14
#define robot_shadow_arm_roll_2	15
#define robot_shadow_arm_up	16
#define robot_shadow_arm_up_through_long	17
#define robot_shadow_arm_up_through_short	18
#define robot_shadow_arm_up_fail_a_1	19
#define robot_shadow_arm_up_fail_a_2	20
#define robot_shadow_arm_up_fail_b_1	21
#define robot_shadow_arm_up_fail_b_2	22
#define robot_shadow_robot_land_1	23
#define robot_shadow_robot_land_2	24
#define robot_shadow_robot_down_just_1	25
#define robot_shadow_robot_down_just_2	26
#define robot_shadow_robot_down_miss_f_1	27
#define robot_shadow_robot_down_miss_f_2	28
#define robot_shadow_robot_down_miss_b_1	29
#define robot_shadow_robot_down_miss_b_2	30
#define robot_shadow_robot_head_1	31
#define robot_shadow_robot_head_2	32
#define robot_shadow_robot_head_roll_1	33
#define robot_shadow_robot_head_roll_2	34
#define robot_shadow_robot_neck_roll_1	35
#define robot_shadow_robot_neck_roll_2	36
#define robot_shadow_robot_body_1	37
#define robot_shadow_robot_body_2	38
#define robot_shadow_robot_up_just_1	39
#define robot_shadow_robot_up_just_2	40
#define robot_shadow_robot_up_miss_f_1	41
#define robot_shadow_robot_up_miss_f_2	42
#define robot_shadow_robot_up_miss_b_1	43
#define robot_shadow_robot_up_miss_b_2	44
#define robot_shadow_robot_up_out_1	45
#define robot_shadow_robot_up_out_2	46
#define robot_shadow_robot_up_through_1	47
#define robot_shadow_robot_up_through_2	48
#define robot_shadow_robot_up_through2_1	49
#define robot_shadow_robot_up_through2_2	50
#define robot_shadow_robot_up_fail_a_1	51
#define robot_shadow_robot_up_fail_a_2	52
#define robot_shadow_robot_up_fail_b_1	53
#define robot_shadow_robot_up_fail_b_2	54
#define robot_shadow_robot_beat_1	55
#define robot_shadow_robot_beat_2	56
#define robot_shadow_crane_open_1	57
#define robot_shadow_crane_open_2	58
#define robot_shadow_crane_down_1	59
#define robot_shadow_crane_down_2	60
#define robot_shadow_crane_up_1	61
#define robot_shadow_crane_up_2	62
