#define sort_hand_ready_l	0
#define sort_hand_ready_r	1
#define sort_hand_hit_just	2
#define sort_hand_hit_out	3
#define sort_hand_catch_l_just_00	4
#define sort_hand_catch_r_just_00	5
#define sort_hand_catch_l_just_01	6
#define sort_hand_catch_r_just_01	7
#define sort_hand_catch_pay_l_just_00	8
#define sort_hand_catch_pay_r_just_00	9
#define sort_hand_catch_l_out	10
#define sort_hand_catch_r_out	11
#define sort_hand_catch_l_bug	12
#define sort_hand_catch_r_bug	13
#define sort_hand_catch_l_miss	14
#define sort_hand_catch_r_miss	15
#define sort_hand_catch_l_through	16
#define sort_hand_catch_r_through	17
#define sort_hand_damage_l	18
#define sort_hand_damage_r	19
#define sort_hand_clap_l	20
#define sort_hand_clap_r	21
#define sort_ball_00	22
#define sort_bug_00	23
#define sort_bug_01	24
#define sort_bug_02	25
#define sort_pay_00	26
#define sort_balls_00	27
#define sort_face_beat	28
#define sort_face_you_normal	29
#define sort_face_you_damage	30
#define sort_face_you_through	31
#define sort_face_you_hit	32
#define sort_face_you_catch	33
#define sort_face_you_two	34
#define sort_face_com_normal	35
#define sort_face_com_hit	36
#define sort_face_com_catch	37
#define sort_face_com_two	38
#define sort_face_00	39
#define sort_face_01	40
#define sort_message_00	41
#define sort_message_01	42
