#define goma_Interval	0
#define goma_A_Press	1
#define goma_A_ReadyForL	2
#define goma_A_ReadyForR	3
#define goma_A_TurnToL	4
#define goma_A_TurnToR	5
#define goma_A_TurnedToL	6
#define goma_A_TurnedToR	7
#define goma_A_RollFromL	8
#define goma_A_RollFromR	9
#define goma_A_RolledFromL	10
#define goma_A_RolledFromR	11
#define goma_B_Press	12
#define goma_B_ReadyForL	13
#define goma_B_ReadyForR	14
#define goma_B_TurnToL	15
#define goma_B_TurnToR	16
#define goma_B_TurnedToL	17
#define goma_B_TurnedToR	18
#define goma_B_RollFromL	19
#define goma_B_RollFromR	20
#define goma_B_RolledFromL	21
#define goma_B_RolledFromR	22
#define goma_face_normal	23
#define goma_face_sad	24
#define goma_face_surprise	25
#define goma_face_angry	26
#define goma_snow	27
#define goma_A_TurnedToL_old	28
#define goma_A_TurnedToR_old	29
