#define frog_frog_sign	0
#define frog_frog_ready	1
#define frog_frog_jump_just	2
#define frog_frog_jump_miss	3
#define frog_frog_jump_out	4
#define frog_frog_through	5
#define frog_leaf_ready	6
#define frog_leaf_jump	7
#define frog_leaf_land_just	8
#define frog_leaf_land_miss	9
#define frog_leaf_through	10
#define frog_girl_sign	11
#define frog_girl_ready_just	12
#define frog_girl_ready_miss	13
#define frog_girl_ready_out_through	14
#define frog_girl_jump_just	15
#define frog_girl_jump_miss	16
#define frog_girl_jump_out_through	17
#define frog_cloud	18
#define frog_splash	19
#define frog_splash_cloud_00	20
#define frog_splash_cloud_01	21
#define frog_bg	22
#define frog_leaves	23
