#define bosa_doll_a_wait	0
#define bosa_doll_a_receive_just	1
#define bosa_doll_a_receive_miss	2
#define bosa_doll_a_receive_out	3
#define bosa_doll_a_rotate_lr	4
#define bosa_doll_a_rotate_rl	5
#define bosa_doll_a_receive_wrong	6
#define bosa_doll_a_through	7
#define bosa_doll_b_wait	8
#define bosa_doll_b_receive_just	9
#define bosa_doll_b_receive_miss	10
#define bosa_doll_b_receive_out	11
#define bosa_doll_b_rotate_lr	12
#define bosa_doll_b_rotate_rl	13
#define bosa_doll_b_receive_wrong	14
#define bosa_doll_b_through	15
#define bosa_stage_wait	16
#define bosa_stage_sink	17
#define bosa_stage_rotate	18
#define bosa_ball_00	19
#define bosa_ball_01	20
#define bosa_guide_turn	21
#define bosa_guide_next	22
#define bosa_shadow	23
#define bosa_hands_under	24
#define bosa_hands_over	25
#define bosa_CellAnim0	26
