#define badminton_bg	0
#define badminton_rocket_l	1
#define badminton_rocket_r	2
#define badminton_you	3
#define badminton_you_ready	4
#define badminton_you_ready_2	5
#define badminton_you_ready_3	6
#define badminton_you_smash	7
#define badminton_you_smash_just	8
#define badminton_you_talk	9
#define badminton_you_catch	10
#define badminton_com	11
#define badminton_com_ready	12
#define badminton_com_smash	13
#define badminton_com_toss	14
#define badminton_com_talk	15
#define badminton_com_talk_short	16
#define badminton_com_catch	17
#define badminton_ball	18
#define badminton_dust	19
#define badminton_you_wind	20
#define badminton_prop	21
#define badminton_hit	22
#define badminton_hit_effect	23
