#define navigator_a_face_talk	0
#define navigator_a_face_blink	1
#define navigator_a_face_look	2
#define navigator_a_face_beat	3
#define navigator_a_body_up	4
#define navigator_a_body_down	5
#define navigator_b_face_talk	6
#define navigator_b_face_blink	7
#define navigator_b_face_look	8
#define navigator_b_face_beat	9
#define navigator_b_body_up	10
#define navigator_b_body_down	11
#define navigator_c_face	12
#define navigator_c_face_just	13
#define navigator_c_face_miss	14
#define navigator_c_face_out	15
#define navigator_c_face_beat	16
#define navigator_c_body_up	17
#define navigator_c_body_down	18
#define navigator_c_body_push_ab	19
#define navigator_balloon_a	20
#define navigator_balloon_ab	21
#define navigator_bg	22
#define navigator_sample	23
