#define ghost_bg_back	0
#define ghost_bg_front	1
#define ghost_bg_tree	2
#define ghost_arrow_ready	3
#define ghost_arrow_shoot	4
#define ghost_arrow_miss	5
#define ghost_ghost_step	6
#define ghost_ghost_just	7
#define ghost_ghost_miss_f	8
#define ghost_ghost_miss_b	9
#define ghost_ghost_through	10
#define ghost_ghost_laugh	11
#define ghost_ghost_damage	12
#define ghost_ghost_timing_inst	13
#define ghost_door_open	14
#define ghost_door_close	15
#define ghost_door_mask	16
#define ghost_ripples	17
#define ghost_rain_fast	18
#define ghost_ripple	19
#define ghost_rain_slow	20
