#define w_date_weasel_weasel_beat	0
#define w_date_weasel_weasel_look	1
#define w_date_weasel_weasel_bad	2
#define w_date_weasel_weasel_hide	3
#define w_date_weasel_weasel_fun	4
#define w_date_weasel_weasel_jump	5
#define w_date_weasel_weasel_miss	6
#define w_date_weasel_weasel_hit	7
#define w_date_weasel_weasel_beat_T	8
#define w_date_weasel_weasel_look_T	9
#define w_date_weasel_weasel_bad_T	10
#define w_date_weasel_weasel_hide_T	11
#define w_date_weasel_weasel_show_T	12
#define w_date_weasel_weasel_talk_T	13
#define w_date_weasel_weasel_blink_T	14
#define w_date_weasel_weasel_fun_T	15
#define w_date_weasel_weasel_jump_T	16
#define w_date_weasel_weasel_miss_T	17
#define w_date_weasel_hole	18
